version: "3"

services:
  bonnie:
    build: .
    command: bundle exec rails s -p 3000 -b '0.0.0.0'
    environment:
      - MONGO_PORT_27017_TCP_ADDR=mongodb
      - MONGO_PORT_27017_TCP_PORT=27017
    ports:
      - "3000:3000"
    links:
      - mongodb:mongo
    env_file: .env-prod
    restart: unless-stopped
  mongodb:
    image: mongo:3.4.5
    volumes:
      - /data/db
    restart: unless-stopped
